namespace Rubicon.Data.Settings.Attributes;

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public class RubiconSettingsSectionAttribute : Attribute
{
	public string SectionName { get; set; }
	public bool AutoGenerated { get; set; }
	public string SectionIconPath { get; set; }

	public RubiconSettingsSectionAttribute(string sectionName, bool autoGenerated = true, string sectionIconPath = null)
	{
		SectionName = sectionName;
		AutoGenerated = autoGenerated; 
		SectionIconPath = sectionIconPath;
	}
}